import dotenv from "dotenv"
dotenv.config({ path: ".env.local" })
import { PrismaClient, EventStatus } from "../generated/prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const adapter = new PrismaPg({ connectionString: process.env.POSTGRES_URL_NON_POOLING! })
const prisma = new PrismaClient({ adapter })

// Helper to create dates easily
function d(year: number, month: number, day: number): Date {
  return new Date(year, month - 1, day)
}

type EventSeed = {
  name: string
  description: string
  location: string
  country: string
  city: string
  venueName: string | null
  startDate: Date
  endDate: Date
  status: EventStatus
  attendees: number
  capacity: number
  cost: number
  revenue: number | null
  currency: string
  category: string
  notes: string | null
}

// ─── 2024 Q2 (Apr–Jun): Company's early days, small events ──────────────────

const events: EventSeed[] = [
  // April 2024 — 2 events
  {
    name: "Spring Networking Mixer",
    description: "Casual networking event for local professionals over drinks and appetizers.",
    location: "Rua Augusta 44, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "The Rooftop Bar",
    startDate: d(2024, 4, 12),
    endDate: d(2024, 4, 12),
    status: "confirmed",
    attendees: 35,
    capacity: 50,
    cost: 1200,
    revenue: 1800,
    currency: "EUR",
    category: "Networking",
    notes: "First event organized by the company. Great turnout for a first attempt.",
  },
  {
    name: "Intro to Digital Marketing Workshop",
    description: "Half-day workshop covering SEO, social media strategy, and content marketing basics.",
    location: "Av. da Liberdade 110, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Impact Hub Lisbon",
    startDate: d(2024, 4, 25),
    endDate: d(2024, 4, 25),
    status: "confirmed",
    attendees: 22,
    capacity: 30,
    cost: 800,
    revenue: 650,
    currency: "EUR",
    category: "Workshop",
    notes: null,
  },

  // May 2024 — 2 events
  {
    name: "Startup Founders Breakfast",
    description: "Early morning meetup for startup founders to share challenges and insights.",
    location: "Rua do Carmo 87, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Copenhagen Coffee Lab",
    startDate: d(2024, 5, 8),
    endDate: d(2024, 5, 8),
    status: "confirmed",
    attendees: 18,
    capacity: 25,
    cost: 450,
    revenue: 580,
    currency: "EUR",
    category: "Networking",
    notes: null,
  },
  {
    name: "UX Design Fundamentals",
    description: "Full-day intensive on user experience design principles, wireframing, and prototyping.",
    location: "Rua de São Paulo 89, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Second Home Lisboa",
    startDate: d(2024, 5, 22),
    endDate: d(2024, 5, 22),
    status: "confirmed",
    attendees: 28,
    capacity: 35,
    cost: 1500,
    revenue: 2100,
    currency: "EUR",
    category: "Workshop",
    notes: "Instructor was excellent. Consider rebooking for Q4.",
  },

  // June 2024 — 3 events
  {
    name: "Summer Product Launch Party",
    description: "Evening celebration for the launch of a fintech product with live demos and cocktails.",
    location: "Praça do Comércio, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Pátio da Galé",
    startDate: d(2024, 6, 7),
    endDate: d(2024, 6, 7),
    status: "confirmed",
    attendees: 85,
    capacity: 100,
    cost: 3500,
    revenue: 4200,
    currency: "EUR",
    category: "Launch Party",
    notes: null,
  },
  {
    name: "Data Analytics Bootcamp",
    description: "Two-day hands-on bootcamp covering Python, pandas, and data visualization.",
    location: "Rua Garrett 25, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Le Wagon Lisbon",
    startDate: d(2024, 6, 14),
    endDate: d(2024, 6, 15),
    status: "confirmed",
    attendees: 20,
    capacity: 24,
    cost: 2800,
    revenue: 3600,
    currency: "EUR",
    category: "Bootcamp",
    notes: null,
  },
  {
    name: "Women in Tech Lisbon",
    description: "Half-day event featuring talks and panels from women leaders in the Portuguese tech scene.",
    location: "Av. Fontes Pereira de Melo 35, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Sana Lisboa Hotel",
    startDate: d(2024, 6, 27),
    endDate: d(2024, 6, 27),
    status: "confirmed",
    attendees: 60,
    capacity: 80,
    cost: 2200,
    revenue: 1700,
    currency: "EUR",
    category: "Conference",
    notes: "Sponsored by two local tech companies.",
  },

  // July 2024 — 2 events
  {
    name: "Remote Work Summit",
    description: "Full-day summit exploring the future of remote and hybrid work models.",
    location: "Rua do Alecrim 21, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Pensão Amor",
    startDate: d(2024, 7, 5),
    endDate: d(2024, 7, 5),
    status: "confirmed",
    attendees: 45,
    capacity: 60,
    cost: 1800,
    revenue: 2400,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Photography & Branding Workshop",
    description: "Half-day workshop on brand photography, visual storytelling, and social media aesthetics.",
    location: "Rua de O Século 11, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Underdogs Gallery",
    startDate: d(2024, 7, 19),
    endDate: d(2024, 7, 19),
    status: "confirmed",
    attendees: 15,
    capacity: 20,
    cost: 650,
    revenue: 850,
    currency: "EUR",
    category: "Workshop",
    notes: null,
  },

  // August 2024 — 2 events
  {
    name: "Summer Hackathon: Green Tech",
    description: "48-hour hackathon focused on building sustainable technology solutions.",
    location: "Rua dos Fanqueiros 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Beta-i",
    startDate: d(2024, 8, 9),
    endDate: d(2024, 8, 11),
    status: "confirmed",
    attendees: 60,
    capacity: 80,
    cost: 4500,
    revenue: 5800,
    currency: "EUR",
    category: "Hackathon",
    notes: "Winner built an app for tracking household carbon footprint.",
  },
  {
    name: "Leadership Dinner — Lisbon Tech Leaders",
    description: "Intimate dinner bringing together CTOs and VPs of Engineering from Lisbon-based companies.",
    location: "Rua das Flores 47, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Belcanto",
    startDate: d(2024, 8, 22),
    endDate: d(2024, 8, 22),
    status: "confirmed",
    attendees: 18,
    capacity: 20,
    cost: 3200,
    revenue: 4100,
    currency: "EUR",
    category: "Dinner",
    notes: "Michelin-starred venue. Very well received.",
  },

  // September 2024 — 3 events
  {
    name: "Back to Business Networking Brunch",
    description: "Post-summer networking brunch for professionals returning from holidays.",
    location: "Av. da Índia 110, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Darwin's Café",
    startDate: d(2024, 9, 6),
    endDate: d(2024, 9, 6),
    status: "confirmed",
    attendees: 40,
    capacity: 50,
    cost: 1400,
    revenue: 1100,
    currency: "EUR",
    category: "Networking",
    notes: null,
  },
  {
    name: "Cloud Infrastructure Workshop",
    description: "Full-day deep dive into AWS, Terraform, and infrastructure as code best practices.",
    location: "Rua Prior do Crato 12, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Porto i/o",
    startDate: d(2024, 9, 13),
    endDate: d(2024, 9, 13),
    status: "confirmed",
    attendees: 25,
    capacity: 30,
    cost: 1800,
    revenue: 2500,
    currency: "EUR",
    category: "Workshop",
    notes: "First event in Porto. Good response, worth expanding there.",
  },
  {
    name: "Lisbon SaaS Meetup #1",
    description: "Monthly meetup for SaaS founders and operators. Lightning talks and Q&A.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2024, 9, 26),
    endDate: d(2024, 9, 26),
    status: "confirmed",
    attendees: 55,
    capacity: 70,
    cost: 900,
    revenue: 1200,
    currency: "EUR",
    category: "Meetup",
    notes: "Inaugural edition of what will become a recurring series.",
  },

  // October 2024 — 4 events
  {
    name: "Web Summit Side Event: AI & Ethics",
    description: "Panel discussion on ethical AI development, held as a side event during Web Summit week.",
    location: "Parque das Nações, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "FIL — Feira Internacional de Lisboa",
    startDate: d(2024, 10, 4),
    endDate: d(2024, 10, 4),
    status: "confirmed",
    attendees: 120,
    capacity: 150,
    cost: 5500,
    revenue: 7200,
    currency: "EUR",
    category: "Panel",
    notes: "Highest attendance yet. Timed perfectly with Web Summit buzz.",
  },
  {
    name: "Product Management Masterclass",
    description: "Two-day intensive masterclass on product strategy, roadmapping, and stakeholder management.",
    location: "Rua do Quelhas 6, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Nova SBE City Campus",
    startDate: d(2024, 10, 11),
    endDate: d(2024, 10, 12),
    status: "confirmed",
    attendees: 32,
    capacity: 40,
    cost: 3800,
    revenue: 4900,
    currency: "EUR",
    category: "Masterclass",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #2",
    description: "Second edition of the monthly SaaS meetup. Topic: pricing strategies.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2024, 10, 24),
    endDate: d(2024, 10, 24),
    status: "confirmed",
    attendees: 62,
    capacity: 70,
    cost: 950,
    revenue: 750,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Berlin Startup Exchange",
    description: "Two-day event connecting the Berlin and Lisbon startup ecosystems with pitches and networking.",
    location: "Oranienstraße 185, Berlin",
    country: "Germany",
    city: "Berlin",
    venueName: "Betahaus Berlin",
    startDate: d(2024, 10, 30),
    endDate: d(2024, 10, 31),
    status: "confirmed",
    attendees: 55,
    capacity: 70,
    cost: 4800,
    revenue: 6500,
    currency: "EUR",
    category: "Conference",
    notes: "First event outside Portugal. Good experience, learned a lot about logistics.",
  },

  // November 2024 — 4 events
  {
    name: "Cybersecurity Awareness Day",
    description: "Full-day event with talks and workshops on cybersecurity threats, phishing, and zero-trust architecture.",
    location: "Rua Braamcamp 12, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Altice Forum Braamcamp",
    startDate: d(2024, 11, 7),
    endDate: d(2024, 11, 7),
    status: "confirmed",
    attendees: 75,
    capacity: 90,
    cost: 3200,
    revenue: 4100,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Porto Startup Crawl",
    description: "Guided walking tour of Porto's startup ecosystem, visiting 5 companies and ending with networking drinks.",
    location: "Various locations, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: null,
    startDate: d(2024, 11, 14),
    endDate: d(2024, 11, 14),
    status: "confirmed",
    attendees: 30,
    capacity: 35,
    cost: 800,
    revenue: 1050,
    currency: "EUR",
    category: "Tour",
    notes: "Very fun format. Participants loved the informal setup.",
  },
  {
    name: "Fintech & Payments Conference",
    description: "Two-day conference on open banking, digital payments, and the future of fintech in Europe.",
    location: "Av. Engenheiro Duarte Pacheco, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro de Congressos de Lisboa",
    startDate: d(2024, 11, 21),
    endDate: d(2024, 11, 22),
    status: "confirmed",
    attendees: 180,
    capacity: 200,
    cost: 12000,
    revenue: 15500,
    currency: "EUR",
    category: "Conference",
    notes: "Biggest event so far. Had 3 sponsors covering 40% of costs.",
  },
  {
    name: "Lisbon SaaS Meetup #3",
    description: "Third edition. Topic: building and scaling customer success teams.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2024, 11, 28),
    endDate: d(2024, 11, 28),
    status: "confirmed",
    attendees: 58,
    capacity: 70,
    cost: 950,
    revenue: 1300,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // December 2024 — 3 events
  {
    name: "End of Year Tech Awards Gala",
    description: "Black-tie gala recognizing the best tech companies and founders of the year in Portugal.",
    location: "Praça do Príncipe Real 26, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Palácio Príncipe Real",
    startDate: d(2024, 12, 6),
    endDate: d(2024, 12, 6),
    status: "confirmed",
    attendees: 150,
    capacity: 160,
    cost: 8500,
    revenue: 10200,
    currency: "EUR",
    category: "Gala",
    notes: "Formal event. Catering was outstanding.",
  },
  {
    name: "Holiday Charity Coding Marathon",
    description: "24-hour coding marathon where teams build tech solutions for local nonprofits.",
    location: "Rua da Prata 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Factory Lisbon",
    startDate: d(2024, 12, 13),
    endDate: d(2024, 12, 14),
    status: "confirmed",
    attendees: 45,
    capacity: 60,
    cost: 3000,
    revenue: 2400,
    currency: "EUR",
    category: "Hackathon",
    notes: "Three nonprofits received working prototypes.",
  },
  {
    name: "Year-End Networking Drinks",
    description: "Relaxed end-of-year gathering for our community to celebrate and connect.",
    location: "Rua Nova do Carvalho 42, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Park Bar",
    startDate: d(2024, 12, 19),
    endDate: d(2024, 12, 19),
    status: "confirmed",
    attendees: 70,
    capacity: 80,
    cost: 1800,
    revenue: 2300,
    currency: "EUR",
    category: "Networking",
    notes: null,
  },

  // ─── 2025: Growth phase — more events, bigger budgets, going international ─

  // January 2025 — 3 events
  {
    name: "New Year Kickoff: 2025 Tech Trends",
    description: "Panel of industry experts discussing the top technology trends for 2025.",
    location: "Rua Alexandre Herculano 38, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Casa do Impacto",
    startDate: d(2025, 1, 10),
    endDate: d(2025, 1, 10),
    status: "confirmed",
    attendees: 85,
    capacity: 100,
    cost: 2800,
    revenue: 3500,
    currency: "EUR",
    category: "Panel",
    notes: null,
  },
  {
    name: "Machine Learning Crash Course",
    description: "Three-day intensive covering ML fundamentals, scikit-learn, and intro to neural networks.",
    location: "Rua da Escola Politécnica 141, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "FCUL — Faculdade de Ciências",
    startDate: d(2025, 1, 20),
    endDate: d(2025, 1, 22),
    status: "confirmed",
    attendees: 30,
    capacity: 35,
    cost: 4200,
    revenue: 5400,
    currency: "EUR",
    category: "Bootcamp",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #4",
    description: "Topic: product-led growth strategies for B2B SaaS.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2025, 1, 30),
    endDate: d(2025, 1, 30),
    status: "confirmed",
    attendees: 65,
    capacity: 70,
    cost: 1000,
    revenue: 1350,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // February 2025 — 4 events
  {
    name: "Valentine's Day Wine & Tech Mixer",
    description: "Casual wine tasting combined with lightning talks on love-related tech (dating apps, relationship AI).",
    location: "Rua da Rosa 107, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "By the Wine",
    startDate: d(2025, 2, 14),
    endDate: d(2025, 2, 14),
    status: "confirmed",
    attendees: 42,
    capacity: 50,
    cost: 1600,
    revenue: 1250,
    currency: "EUR",
    category: "Networking",
    notes: "Fun theme. Lots of social media engagement.",
  },
  {
    name: "DevOps Days Lisbon",
    description: "Two-day community conference on DevOps culture, CI/CD, observability, and platform engineering.",
    location: "Av. Dom João II, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Altice Arena — Side Hall",
    startDate: d(2025, 2, 20),
    endDate: d(2025, 2, 21),
    status: "confirmed",
    attendees: 220,
    capacity: 250,
    cost: 18000,
    revenue: 24000,
    currency: "EUR",
    category: "Conference",
    notes: "Sold out early. Need a larger venue next time.",
  },
  {
    name: "Amsterdam Founders Meetup",
    description: "Evening networking event for Portuguese and Dutch founders in Amsterdam's startup scene.",
    location: "Keizersgracht 126, Amsterdam",
    country: "Netherlands",
    city: "Amsterdam",
    venueName: "TQ — The Tech Quarter",
    startDate: d(2025, 2, 25),
    endDate: d(2025, 2, 25),
    status: "confirmed",
    attendees: 35,
    capacity: 50,
    cost: 2200,
    revenue: 2900,
    currency: "EUR",
    category: "Networking",
    notes: "Testing the Amsterdam market. Decent turnout for a first event.",
  },
  {
    name: "Porto Tech Talks #1",
    description: "Inaugural edition of a new monthly meetup in Porto. Three 20-min talks on frontend, backend, and mobile.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 2, 27),
    endDate: d(2025, 2, 27),
    status: "confirmed",
    attendees: 38,
    capacity: 50,
    cost: 750,
    revenue: 980,
    currency: "EUR",
    category: "Meetup",
    notes: "Starting a Porto series to complement Lisbon events.",
  },

  // March 2025 — 5 events
  {
    name: "International Women's Day: Women Who Code",
    description: "Full-day event celebrating women in tech with talks, workshops, and mentoring sessions.",
    location: "Rua de São Bento 209, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Assembleia da República — Event Hall",
    startDate: d(2025, 3, 8),
    endDate: d(2025, 3, 8),
    status: "confirmed",
    attendees: 130,
    capacity: 150,
    cost: 5500,
    revenue: 7100,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Paris Tech Connect",
    description: "Full-day event bridging the French and Portuguese tech ecosystems with talks and networking.",
    location: "11 Rue de Cambrai, Paris",
    country: "France",
    city: "Paris",
    venueName: "Station F",
    startDate: d(2025, 3, 14),
    endDate: d(2025, 3, 14),
    status: "confirmed",
    attendees: 80,
    capacity: 100,
    cost: 5800,
    revenue: 7500,
    currency: "EUR",
    category: "Conference",
    notes: "Station F is an incredible venue. Partnership with La French Tech.",
  },
  {
    name: "European Startup Retreat",
    description: "Four-day retreat for founders including strategy workshops, outdoor activities, and peer mentoring.",
    location: "Praia da Falésia, Albufeira",
    country: "Portugal",
    city: "Albufeira",
    venueName: "Pine Cliffs Resort",
    startDate: d(2025, 3, 18),
    endDate: d(2025, 3, 21),
    status: "confirmed",
    attendees: 40,
    capacity: 45,
    cost: 22000,
    revenue: 28500,
    currency: "EUR",
    category: "Retreat",
    notes: "Premium event. All-inclusive accommodation. Extremely positive feedback.",
  },
  {
    name: "Lisbon SaaS Meetup #5",
    description: "Topic: fundraising in 2025 — VC landscape and alternatives.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2025, 3, 27),
    endDate: d(2025, 3, 27),
    status: "confirmed",
    attendees: 68,
    capacity: 70,
    cost: 1000,
    revenue: 800,
    currency: "EUR",
    category: "Meetup",
    notes: "Almost at capacity. Need to consider a larger venue.",
  },
  {
    name: "Porto Tech Talks #2",
    description: "Topics: Rust in production, GraphQL best practices, and cross-platform mobile development.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 3, 28),
    endDate: d(2025, 3, 28),
    status: "confirmed",
    attendees: 44,
    capacity: 50,
    cost: 800,
    revenue: 1100,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // April 2025 — 5 events
  {
    name: "API Design & Integration Summit",
    description: "Full-day summit on REST, GraphQL, gRPC, and API-first design patterns.",
    location: "Rua do Salitre 1, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Hotel Tivoli Avenida",
    startDate: d(2025, 4, 3),
    endDate: d(2025, 4, 3),
    status: "confirmed",
    attendees: 95,
    capacity: 120,
    cost: 4500,
    revenue: 5800,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Creative Coding Night",
    description: "Evening event combining generative art, creative coding with p5.js, and electronic music.",
    location: "Rua da Cintura do Porto de Lisboa, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Village Underground Lisboa",
    startDate: d(2025, 4, 11),
    endDate: d(2025, 4, 11),
    status: "confirmed",
    attendees: 90,
    capacity: 120,
    cost: 2800,
    revenue: 3600,
    currency: "EUR",
    category: "Social",
    notes: "Live coding performances were the highlight.",
  },
  {
    name: "Earth Day Sustainability in Tech",
    description: "Half-day event on green computing, sustainable software engineering, and carbon-aware development.",
    location: "Rua Victor Cordon 10, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Galeria Victor Cordon",
    startDate: d(2025, 4, 22),
    endDate: d(2025, 4, 22),
    status: "confirmed",
    attendees: 50,
    capacity: 60,
    cost: 1600,
    revenue: 2100,
    currency: "EUR",
    category: "Forum",
    notes: null,
  },
  {
    name: "Porto Tech Talks #3",
    description: "Topics: event-driven architecture, design systems, and AI-assisted testing.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 4, 24),
    endDate: d(2025, 4, 24),
    status: "confirmed",
    attendees: 48,
    capacity: 50,
    cost: 800,
    revenue: 650,
    currency: "EUR",
    category: "Meetup",
    notes: "Fully booked. Porto series is growing.",
  },
  {
    name: "Lisbon SaaS Meetup #6",
    description: "Topic: international expansion — going from Portugal to global markets.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2025, 4, 28),
    endDate: d(2025, 4, 28),
    status: "confirmed",
    attendees: 70,
    capacity: 80,
    cost: 1100,
    revenue: 1450,
    currency: "EUR",
    category: "Meetup",
    notes: "Moved to larger room at the venue.",
  },

  // May 2025 — 5 events
  {
    name: "Scale-Up Leadership Forum",
    description: "Two-day forum for scale-up CEOs and C-suite on growth, culture, and organizational design.",
    location: "Av. Marginal, Cascais",
    country: "Portugal",
    city: "Cascais",
    venueName: "Hotel Cascais Miragem",
    startDate: d(2025, 5, 8),
    endDate: d(2025, 5, 9),
    status: "confirmed",
    attendees: 60,
    capacity: 70,
    cost: 9500,
    revenue: 12000,
    currency: "EUR",
    category: "Forum",
    notes: "Executive-level event. Catered lunch and dinner included.",
  },
  {
    name: "React & Next.js Conference Lisbon",
    description: "Three-day conference for frontend developers featuring talks, workshops, and hackathon.",
    location: "Rua da Junqueira 30, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro Cultural de Belém",
    startDate: d(2025, 5, 14),
    endDate: d(2025, 5, 16),
    status: "confirmed",
    attendees: 350,
    capacity: 400,
    cost: 35000,
    revenue: 45000,
    currency: "EUR",
    category: "Conference",
    notes: "Flagship technical conference. International speakers from Vercel, Meta, and Shopify.",
  },
  {
    name: "London Fintech Networking Night",
    description: "Evening networking event for fintech founders and investors in London's financial district.",
    location: "1 Poultry, London",
    country: "United Kingdom",
    city: "London",
    venueName: "Coq d'Argent",
    startDate: d(2025, 5, 21),
    endDate: d(2025, 5, 21),
    status: "confirmed",
    attendees: 65,
    capacity: 80,
    cost: 4200,
    revenue: 5500,
    currency: "GBP",
    category: "Networking",
    notes: "Strong interest from London-based Portuguese founders.",
  },
  {
    name: "Lisbon SaaS Meetup #7",
    description: "Topic: AI-powered SaaS — building and integrating LLM features.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2025, 5, 29),
    endDate: d(2025, 5, 29),
    status: "confirmed",
    attendees: 75,
    capacity: 80,
    cost: 1100,
    revenue: 1400,
    currency: "EUR",
    category: "Meetup",
    notes: "Highest attendance for the SaaS meetup series.",
  },
  {
    name: "Porto Tech Talks #4",
    description: "Topics: observability, edge computing, and building developer platforms.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 5, 30),
    endDate: d(2025, 5, 30),
    status: "confirmed",
    attendees: 50,
    capacity: 55,
    cost: 850,
    revenue: 680,
    currency: "EUR",
    category: "Meetup",
    notes: "Porto venue at capacity, looking for bigger space.",
  },

  // June 2025 — 5 events
  {
    name: "AI & Automation Expo",
    description: "Two-day expo showcasing AI tools, automation platforms, and robotics demonstrations.",
    location: "Parque das Nações, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "FIL — Feira Internacional de Lisboa",
    startDate: d(2025, 6, 5),
    endDate: d(2025, 6, 6),
    status: "confirmed",
    attendees: 400,
    capacity: 500,
    cost: 42000,
    revenue: 55000,
    currency: "EUR",
    category: "Expo",
    notes: "Largest event to date. 20 exhibitors and 15 sponsors.",
  },
  {
    name: "Open Source Contribution Day",
    description: "Full-day event where participants contribute to open source projects with mentorship from maintainers.",
    location: "Rua da Prata 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Factory Lisbon",
    startDate: d(2025, 6, 12),
    endDate: d(2025, 6, 12),
    status: "confirmed",
    attendees: 55,
    capacity: 60,
    cost: 1500,
    revenue: 1950,
    currency: "EUR",
    category: "Hackathon",
    notes: null,
  },
  {
    name: "New York Tech Bridge",
    description: "Two-day event connecting the NYC and European tech ecosystems. Hosted in Manhattan.",
    location: "335 Madison Ave, New York",
    country: "United States",
    city: "New York",
    venueName: "Convene Midtown East",
    startDate: d(2025, 6, 18),
    endDate: d(2025, 6, 19),
    status: "confirmed",
    attendees: 120,
    capacity: 150,
    cost: 28000,
    revenue: 36000,
    currency: "USD",
    category: "Conference",
    notes: "First US event. Very expensive but strategically important for brand.",
  },
  {
    name: "Lisbon SaaS Meetup #8",
    description: "Topic: customer retention and churn reduction tactics.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2025, 6, 26),
    endDate: d(2025, 6, 26),
    status: "confirmed",
    attendees: 72,
    capacity: 80,
    cost: 1100,
    revenue: 1500,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Summer Solstice Rooftop Party",
    description: "Rooftop party with DJ, food trucks, and startup pitches at sunset.",
    location: "Cais do Sodré, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LUMI Rooftop",
    startDate: d(2025, 6, 21),
    endDate: d(2025, 6, 21),
    status: "confirmed",
    attendees: 160,
    capacity: 180,
    cost: 5500,
    revenue: 7000,
    currency: "EUR",
    category: "Social",
    notes: null,
  },

  // July 2025 — 4 events
  {
    name: "Deep Tech Investment Day",
    description: "Full-day event connecting deep tech startups with investors. Pitch sessions and 1-on-1 meetings.",
    location: "Av. da Liberdade 245, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Corinthia Lisbon",
    startDate: d(2025, 7, 3),
    endDate: d(2025, 7, 3),
    status: "confirmed",
    attendees: 110,
    capacity: 130,
    cost: 7500,
    revenue: 9800,
    currency: "EUR",
    category: "Summit",
    notes: "3 startups secured follow-up meetings with VCs.",
  },
  {
    name: "Cloud Native Portugal",
    description: "Two-day conference on Kubernetes, service mesh, serverless, and cloud native patterns.",
    location: "Rua Ivens 3, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Hotel do Chiado",
    startDate: d(2025, 7, 10),
    endDate: d(2025, 7, 11),
    status: "confirmed",
    attendees: 180,
    capacity: 200,
    cost: 15000,
    revenue: 19500,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Algarve Tech Retreat",
    description: "Five-day retreat combining tech talks, wellness activities, and team building in the Algarve.",
    location: "Praia da Marinha, Lagoa",
    country: "Portugal",
    city: "Lagoa",
    venueName: "Tivoli Carvoeiro",
    startDate: d(2025, 7, 21),
    endDate: d(2025, 7, 25),
    status: "confirmed",
    attendees: 50,
    capacity: 55,
    cost: 28000,
    revenue: 22000,
    currency: "EUR",
    category: "Retreat",
    notes: "Premium 5-day retreat. Yoga, surfing, hiking included.",
  },
  {
    name: "Porto Tech Talks #5",
    description: "Topics: TypeScript 5.x deep dive, Deno 2.0 in production, and Postgres performance.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 7, 31),
    endDate: d(2025, 7, 31),
    status: "confirmed",
    attendees: 52,
    capacity: 55,
    cost: 900,
    revenue: 1200,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // August 2025 — 4 events
  {
    name: "Summer Hackathon: ClimateTech",
    description: "48-hour hackathon building solutions for climate change, renewable energy, and sustainable living.",
    location: "Rua dos Fanqueiros 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Beta-i",
    startDate: d(2025, 8, 8),
    endDate: d(2025, 8, 10),
    status: "confirmed",
    attendees: 80,
    capacity: 100,
    cost: 6000,
    revenue: 7800,
    currency: "EUR",
    category: "Hackathon",
    notes: null,
  },
  {
    name: "San Francisco AI Mixer",
    description: "Evening networking event for AI founders and engineers in the Bay Area.",
    location: "480 2nd St, San Francisco",
    country: "United States",
    city: "San Francisco",
    venueName: "South Park Commons",
    startDate: d(2025, 8, 14),
    endDate: d(2025, 8, 14),
    status: "confirmed",
    attendees: 75,
    capacity: 100,
    cost: 8000,
    revenue: 10500,
    currency: "USD",
    category: "Networking",
    notes: "Great connections in the SF AI scene. Several VCs attended.",
  },
  {
    name: "Data Engineering Summit",
    description: "Full-day summit on data pipelines, lakehouse architecture, dbt, and real-time streaming.",
    location: "Av. Brasília, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "MAAT — Museum of Art, Architecture and Technology",
    startDate: d(2025, 8, 19),
    endDate: d(2025, 8, 19),
    status: "confirmed",
    attendees: 120,
    capacity: 140,
    cost: 5800,
    revenue: 7400,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #9",
    description: "Topic: bootstrapping vs. raising — real stories from Portuguese founders.",
    location: "Rua de Santa Catarina 4, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Startup Lisboa",
    startDate: d(2025, 8, 28),
    endDate: d(2025, 8, 28),
    status: "confirmed",
    attendees: 78,
    capacity: 80,
    cost: 1200,
    revenue: 950,
    currency: "EUR",
    category: "Meetup",
    notes: "Sold out. Waiting list of 15 people.",
  },

  // September 2025 — 6 events
  {
    name: "Back to Business Summit 2025",
    description: "Two-day summit kicking off the business season with keynotes, panels, and workshops.",
    location: "Av. Engenheiro Duarte Pacheco, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro de Congressos de Lisboa",
    startDate: d(2025, 9, 4),
    endDate: d(2025, 9, 5),
    status: "confirmed",
    attendees: 280,
    capacity: 300,
    cost: 22000,
    revenue: 28000,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Design Systems Conference",
    description: "Full-day conference on building, scaling, and governing design systems.",
    location: "Rua da Junqueira 30, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro Cultural de Belém",
    startDate: d(2025, 9, 11),
    endDate: d(2025, 9, 11),
    status: "confirmed",
    attendees: 140,
    capacity: 160,
    cost: 8000,
    revenue: 10400,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Women in Leadership Retreat",
    description: "Three-day retreat for women in leadership roles. Coaching, strategy workshops, and wellness.",
    location: "Serra da Arrábida, Setúbal",
    country: "Portugal",
    city: "Setúbal",
    venueName: "Quinta da Arrábida",
    startDate: d(2025, 9, 15),
    endDate: d(2025, 9, 17),
    status: "confirmed",
    attendees: 30,
    capacity: 35,
    cost: 14000,
    revenue: 18000,
    currency: "EUR",
    category: "Retreat",
    notes: "Intimate retreat format works very well for this audience.",
  },
  {
    name: "Startup Pitch Night — Fall Edition",
    description: "Evening event where 10 early-stage startups pitch to a panel of investors and an audience of 200+.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2025, 9, 18),
    endDate: d(2025, 9, 18),
    status: "confirmed",
    attendees: 210,
    capacity: 250,
    cost: 4500,
    revenue: 5800,
    currency: "EUR",
    category: "Pitch Night",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #10",
    description: "Special 10th edition! Retrospective panel with all previous speakers.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2025, 9, 25),
    endDate: d(2025, 9, 25),
    status: "confirmed",
    attendees: 110,
    capacity: 120,
    cost: 2500,
    revenue: 3200,
    currency: "EUR",
    category: "Meetup",
    notes: "Moved to LX Factory for the anniversary edition.",
  },
  {
    name: "Porto Tech Talks #6",
    description: "Topics: WebAssembly, htmx, and real-world AI agent architectures.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 9, 26),
    endDate: d(2025, 9, 26),
    status: "confirmed",
    attendees: 55,
    capacity: 60,
    cost: 950,
    revenue: 1250,
    currency: "EUR",
    category: "Meetup",
    notes: "Moved to larger space within venue.",
  },

  // October 2025 — 6 events
  {
    name: "Web Summit Side Event: Future of Work",
    description: "Full-day side event during Web Summit week, focusing on AI at work, 4-day workweek, and distributed teams.",
    location: "Parque das Nações, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "FIL — Feira Internacional de Lisboa",
    startDate: d(2025, 10, 3),
    endDate: d(2025, 10, 3),
    status: "confirmed",
    attendees: 250,
    capacity: 300,
    cost: 12000,
    revenue: 15500,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Platform Engineering Day",
    description: "Full-day event on internal developer platforms, golden paths, and developer experience.",
    location: "Rua Castilho 75, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Edifício Castilho",
    startDate: d(2025, 10, 9),
    endDate: d(2025, 10, 9),
    status: "confirmed",
    attendees: 95,
    capacity: 110,
    cost: 4800,
    revenue: 3800,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Madrid–Lisbon Tech Bridge",
    description: "Two-day event bridging the Spanish and Portuguese tech ecosystems. Day 1 in Madrid, Day 2 virtually.",
    location: "Paseo de la Castellana 89, Madrid",
    country: "Spain",
    city: "Madrid",
    venueName: "Google for Startups Campus Madrid",
    startDate: d(2025, 10, 16),
    endDate: d(2025, 10, 17),
    status: "confirmed",
    attendees: 140,
    capacity: 160,
    cost: 11000,
    revenue: 14200,
    currency: "EUR",
    category: "Conference",
    notes: "Partnership with Madrid tech community. Cross-border events resonate well.",
  },
  {
    name: "Cybersecurity Summit 2025",
    description: "Two-day summit on threat landscape, zero-trust, and security engineering practices.",
    location: "Av. Fontes Pereira de Melo 35, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Sana Lisboa Hotel",
    startDate: d(2025, 10, 14),
    endDate: d(2025, 10, 15),
    status: "confirmed",
    attendees: 190,
    capacity: 220,
    cost: 16000,
    revenue: 20500,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #11",
    description: "Topic: building in public — transparency as a growth strategy.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2025, 10, 23),
    endDate: d(2025, 10, 23),
    status: "confirmed",
    attendees: 105,
    capacity: 120,
    cost: 2200,
    revenue: 2900,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Porto Tech Talks #7",
    description: "Topics: micro-frontends, Bun runtime, and building with LLMs.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 10, 30),
    endDate: d(2025, 10, 30),
    status: "confirmed",
    attendees: 58,
    capacity: 60,
    cost: 950,
    revenue: 1250,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // November 2025 — 6 events
  {
    name: "TypeScript Conference Portugal",
    description: "Three-day conference with workshops and talks on TypeScript, type systems, and developer tooling.",
    location: "Rua da Junqueira 30, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro Cultural de Belém",
    startDate: d(2025, 11, 5),
    endDate: d(2025, 11, 7),
    status: "confirmed",
    attendees: 300,
    capacity: 350,
    cost: 32000,
    revenue: 42000,
    currency: "EUR",
    category: "Conference",
    notes: "Second big technical conference. Speakers from Microsoft, Deno, and Effect.",
  },
  {
    name: "GreenTech Awards Dinner",
    description: "Annual awards dinner recognizing sustainable technology innovation in Portugal.",
    location: "Praça do Príncipe Real 26, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Palácio Príncipe Real",
    startDate: d(2025, 11, 13),
    endDate: d(2025, 11, 13),
    status: "confirmed",
    attendees: 140,
    capacity: 160,
    cost: 9000,
    revenue: 11500,
    currency: "EUR",
    category: "Gala",
    notes: null,
  },
  {
    name: "Copenhagen Innovation Exchange",
    description: "Two-day event connecting Nordic and Southern European tech ecosystems.",
    location: "Njalsgade 19D, Copenhagen",
    country: "Denmark",
    city: "Copenhagen",
    venueName: "Rainmaking Loft",
    startDate: d(2025, 11, 18),
    endDate: d(2025, 11, 19),
    status: "confirmed",
    attendees: 80,
    capacity: 100,
    cost: 9500,
    revenue: 12200,
    currency: "EUR",
    category: "Conference",
    notes: "Nordic market is very receptive. Strong VC presence.",
  },
  {
    name: "Lisbon SaaS Meetup #12",
    description: "Topic: year in review — what worked and what didn't in Portuguese SaaS.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2025, 11, 27),
    endDate: d(2025, 11, 27),
    status: "confirmed",
    attendees: 115,
    capacity: 120,
    cost: 2400,
    revenue: 3100,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Porto Tech Talks #8",
    description: "Topics: local-first software, SQLite in production, and developer advocacy.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2025, 11, 28),
    endDate: d(2025, 11, 28),
    status: "confirmed",
    attendees: 60,
    capacity: 65,
    cost: 1000,
    revenue: 1350,
    currency: "EUR",
    category: "Meetup",
    notes: "Upgraded to larger room.",
  },
  {
    name: "Healthtech & Biotech Forum",
    description: "Two-day forum on digital therapeutics, precision medicine, and healthtech innovation.",
    location: "Av. Professor Doutor Aníbal Cavaco Silva, Oeiras",
    country: "Portugal",
    city: "Oeiras",
    venueName: "Taguspark",
    startDate: d(2025, 11, 20),
    endDate: d(2025, 11, 21),
    status: "confirmed",
    attendees: 120,
    capacity: 140,
    cost: 8500,
    revenue: 6800,
    currency: "EUR",
    category: "Forum",
    notes: null,
  },

  // December 2025 — 4 events
  {
    name: "End of Year Tech Gala 2025",
    description: "Black-tie awards gala celebrating the best of Portuguese tech in 2025.",
    location: "Praça do Príncipe Real 26, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Palácio Príncipe Real",
    startDate: d(2025, 12, 5),
    endDate: d(2025, 12, 5),
    status: "confirmed",
    attendees: 200,
    capacity: 220,
    cost: 12000,
    revenue: 15500,
    currency: "EUR",
    category: "Gala",
    notes: "Bigger and better than 2024 edition.",
  },
  {
    name: "AI Agents Workshop",
    description: "Full-day hands-on workshop on building AI agents with LLMs, tool use, and multi-agent systems.",
    location: "Rua da Prata 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Factory Lisbon",
    startDate: d(2025, 12, 11),
    endDate: d(2025, 12, 11),
    status: "confirmed",
    attendees: 40,
    capacity: 45,
    cost: 3200,
    revenue: 4100,
    currency: "EUR",
    category: "Workshop",
    notes: "Very hands-on. Each participant built a working agent.",
  },
  {
    name: "Holiday Charity Hackathon 2025",
    description: "Second annual 24-hour charity coding marathon benefiting local NGOs.",
    location: "Rua da Prata 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Factory Lisbon",
    startDate: d(2025, 12, 12),
    endDate: d(2025, 12, 13),
    status: "confirmed",
    attendees: 65,
    capacity: 80,
    cost: 4500,
    revenue: 5800,
    currency: "EUR",
    category: "Hackathon",
    notes: "Five NGOs received working solutions this year.",
  },
  {
    name: "Year-End Community Celebration",
    description: "Relaxed end-of-year party for the entire community with food, drinks, and live music.",
    location: "Rua Nova do Carvalho 42, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Park Bar",
    startDate: d(2025, 12, 18),
    endDate: d(2025, 12, 18),
    status: "confirmed",
    attendees: 120,
    capacity: 140,
    cost: 3800,
    revenue: 4900,
    currency: "EUR",
    category: "Social",
    notes: null,
  },

  // ─── 2026: Matured company — bigger events, more international ─────────────

  // January 2026 — 5 events
  {
    name: "2026 Tech Outlook Summit",
    description: "Two-day summit exploring the technology landscape for 2026 and beyond.",
    location: "Av. Engenheiro Duarte Pacheco, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro de Congressos de Lisboa",
    startDate: d(2026, 1, 8),
    endDate: d(2026, 1, 9),
    status: "confirmed",
    attendees: 320,
    capacity: 350,
    cost: 25000,
    revenue: 32000,
    currency: "EUR",
    category: "Summit",
    notes: "Record attendance for a January event.",
  },
  {
    name: "Engineering Management Bootcamp",
    description: "Three-day bootcamp for new and aspiring engineering managers on team building, 1:1s, and delivery.",
    location: "Rua do Salitre 1, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Hotel Tivoli Avenida",
    startDate: d(2026, 1, 14),
    endDate: d(2026, 1, 16),
    status: "confirmed",
    attendees: 35,
    capacity: 40,
    cost: 7500,
    revenue: 9600,
    currency: "EUR",
    category: "Bootcamp",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #13",
    description: "Topic: AI-native SaaS — building products with AI at the core.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2026, 1, 22),
    endDate: d(2026, 1, 22),
    status: "confirmed",
    attendees: 120,
    capacity: 130,
    cost: 2800,
    revenue: 3600,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Porto Developer Conference",
    description: "Two-day developer conference in Porto covering full-stack development, DevOps, and AI/ML.",
    location: "Rua das Flores 27, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Palácio das Artes",
    startDate: d(2026, 1, 29),
    endDate: d(2026, 1, 30),
    status: "confirmed",
    attendees: 200,
    capacity: 220,
    cost: 18000,
    revenue: 23500,
    currency: "EUR",
    category: "Conference",
    notes: "First multi-day conference in Porto. Huge success.",
  },
  {
    name: "FinOps & Cloud Cost Optimization",
    description: "Half-day workshop on managing cloud spend, FinOps practices, and cost attribution.",
    location: "Rua Castilho 75, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Edifício Castilho",
    startDate: d(2026, 1, 20),
    endDate: d(2026, 1, 20),
    status: "confirmed",
    attendees: 45,
    capacity: 50,
    cost: 1800,
    revenue: 2400,
    currency: "EUR",
    category: "Workshop",
    notes: null,
  },

  // February 2026 — 6 events
  {
    name: "AI in Healthcare Conference",
    description: "Two-day conference on AI applications in diagnostics, drug discovery, and patient care.",
    location: "Av. Fontes Pereira de Melo 35, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Sana Lisboa Hotel",
    startDate: d(2026, 2, 5),
    endDate: d(2026, 2, 6),
    status: "confirmed",
    attendees: 180,
    capacity: 200,
    cost: 15000,
    revenue: 19000,
    currency: "EUR",
    category: "Conference",
    notes: null,
  },
  {
    name: "Startup Funding Bootcamp",
    description: "Two-day bootcamp on fundraising: pitch deck, financial modeling, term sheets, and negotiation.",
    location: "Rua Alexandre Herculano 38, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Casa do Impacto",
    startDate: d(2026, 2, 12),
    endDate: d(2026, 2, 13),
    status: "confirmed",
    attendees: 28,
    capacity: 30,
    cost: 4200,
    revenue: 5400,
    currency: "EUR",
    category: "Bootcamp",
    notes: null,
  },
  {
    name: "Barcelona–Lisbon Startup Exchange",
    description: "Two-day cross-border event connecting Barcelona and Lisbon startup ecosystems.",
    location: "Carrer de Pallars 190, Barcelona",
    country: "Spain",
    city: "Barcelona",
    venueName: "MOB Bailén",
    startDate: d(2026, 2, 17),
    endDate: d(2026, 2, 18),
    status: "confirmed",
    attendees: 160,
    capacity: 180,
    cost: 13000,
    revenue: 16800,
    currency: "EUR",
    category: "Conference",
    notes: "Partnership with Barcelona Activa. Iberian events are a hit.",
  },
  {
    name: "Developer Experience Summit",
    description: "Full-day summit on DX tooling, developer portals, documentation, and internal platforms.",
    location: "Rua da Junqueira 30, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro Cultural de Belém",
    startDate: d(2026, 2, 19),
    endDate: d(2026, 2, 19),
    status: "confirmed",
    attendees: 160,
    capacity: 180,
    cost: 8500,
    revenue: 11000,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #14",
    description: "Topic: vertical SaaS — going deep in niche markets.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2026, 2, 26),
    endDate: d(2026, 2, 26),
    status: "confirmed",
    attendees: 118,
    capacity: 130,
    cost: 2800,
    revenue: 3600,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Porto Tech Talks #9",
    description: "Topics: Elixir & Phoenix, edge functions, and building multi-tenant SaaS.",
    location: "Rua de Cândido dos Reis 81, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Selina Porto",
    startDate: d(2026, 2, 27),
    endDate: d(2026, 2, 27),
    status: "confirmed",
    attendees: 62,
    capacity: 65,
    cost: 1000,
    revenue: 1300,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // March 2026 — ongoing & upcoming events
  {
    name: "International Women's Day: Tech Leaders Forum",
    description: "Full-day forum celebrating women in technology with keynotes, panels, and mentorship sessions.",
    location: "Rua de São Bento 209, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Assembleia da República — Event Hall",
    startDate: d(2026, 3, 8),
    endDate: d(2026, 3, 8),
    status: "confirmed",
    attendees: 180,
    capacity: 200,
    cost: 8000,
    revenue: 10200,
    currency: "EUR",
    category: "Forum",
    notes: null,
  },
  {
    name: "European AI Conference",
    description: "Four-day international conference on AI research, applications, and policy. Keynotes from leading researchers.",
    location: "Parque das Nações, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "FIL — Feira Internacional de Lisboa",
    startDate: d(2026, 3, 10),
    endDate: d(2026, 3, 27),
    status: "confirmed",
    attendees: 0,
    capacity: 600,
    cost: 75000,
    revenue: null,
    currency: "EUR",
    category: "Conference",
    notes: "Largest event ever. International speakers from DeepMind, OpenAI, and Anthropic. Currently ongoing.",
  },
  {
    name: "Lisbon SaaS Meetup #15",
    description: "Topic: developer-first SaaS and API-as-a-product strategies.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2026, 3, 26),
    endDate: d(2026, 3, 26),
    status: "confirmed",
    attendees: 0,
    capacity: 130,
    cost: 3000,
    revenue: null,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },
  {
    name: "Porto Tech Talks #10",
    description: "Special 10th edition! Retrospective + live coding demos.",
    location: "Rua das Flores 27, Porto",
    country: "Portugal",
    city: "Porto",
    venueName: "Palácio das Artes",
    startDate: d(2026, 3, 27),
    endDate: d(2026, 3, 27),
    status: "confirmed",
    attendees: 0,
    capacity: 80,
    cost: 1500,
    revenue: null,
    currency: "EUR",
    category: "Meetup",
    notes: "Anniversary edition at larger Porto venue.",
  },

  // April 2026 — upcoming
  {
    name: "Spring Startup Retreat",
    description: "Five-day retreat for founders in the Alentejo countryside. Strategy, wellness, and peer support.",
    location: "Herdade da Malhadinha Nova, Albernoa",
    country: "Portugal",
    city: "Beja",
    venueName: "Malhadinha Nova",
    startDate: d(2026, 4, 6),
    endDate: d(2026, 4, 10),
    status: "confirmed",
    attendees: 0,
    capacity: 40,
    cost: 30000,
    revenue: null,
    currency: "EUR",
    category: "Retreat",
    notes: "Premium all-inclusive retreat. Vineyard setting.",
  },
  {
    name: "Platform Engineering Europe",
    description: "Three-day conference on internal developer platforms, Backstage, Kratix, and platform teams.",
    location: "Av. Engenheiro Duarte Pacheco, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro de Congressos de Lisboa",
    startDate: d(2026, 4, 15),
    endDate: d(2026, 4, 17),
    status: "confirmed",
    attendees: 0,
    capacity: 400,
    cost: 45000,
    revenue: null,
    currency: "EUR",
    category: "Conference",
    notes: "Aiming to be a reference European conference for platform engineering.",
  },
  {
    name: "Earth Day Sustainability Summit",
    description: "Full-day summit on sustainable technology, green software, and ESG reporting tools.",
    location: "Rua Rodrigo da Fonseca 11, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Fundação Calouste Gulbenkian",
    startDate: d(2026, 4, 22),
    endDate: d(2026, 4, 22),
    status: "draft",
    attendees: 0,
    capacity: 180,
    cost: 9000,
    revenue: null,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Lisbon SaaS Meetup #16",
    description: "Topic: PLG meets sales — hybrid go-to-market strategies.",
    location: "Av. 24 de Julho 49, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "LX Factory",
    startDate: d(2026, 4, 23),
    endDate: d(2026, 4, 23),
    status: "draft",
    attendees: 0,
    capacity: 130,
    cost: 3000,
    revenue: null,
    currency: "EUR",
    category: "Meetup",
    notes: null,
  },

  // May 2026 — upcoming
  {
    name: "React Summit Lisbon 2026",
    description: "Four-day flagship React conference. Workshops, talks, and community day.",
    location: "Rua da Junqueira 30, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Centro Cultural de Belém",
    startDate: d(2026, 5, 13),
    endDate: d(2026, 5, 16),
    status: "confirmed",
    attendees: 0,
    capacity: 500,
    cost: 55000,
    revenue: null,
    currency: "EUR",
    category: "Conference",
    notes: "Second edition. Partnering with React Summit brand.",
  },
  {
    name: "Scale-Up CEO Forum 2026",
    description: "Two-day exclusive forum for scale-up CEOs. By invitation only.",
    location: "Av. Marginal, Cascais",
    country: "Portugal",
    city: "Cascais",
    venueName: "Hotel Cascais Miragem",
    startDate: d(2026, 5, 21),
    endDate: d(2026, 5, 22),
    status: "confirmed",
    attendees: 0,
    capacity: 80,
    cost: 14000,
    revenue: null,
    currency: "EUR",
    category: "Forum",
    notes: null,
  },
  {
    name: "Chicago SaaS Connect",
    description: "Two-day event bringing together European and Midwest US SaaS founders.",
    location: "222 Merchandise Mart Plaza, Chicago",
    country: "United States",
    city: "Chicago",
    venueName: "1871 — Chicago's Tech Hub",
    startDate: d(2026, 5, 28),
    endDate: d(2026, 5, 29),
    status: "confirmed",
    attendees: 0,
    capacity: 120,
    cost: 22000,
    revenue: null,
    currency: "USD",
    category: "Conference",
    notes: "Expanding US presence to the Midwest market.",
  },

  // June 2026 — upcoming
  {
    name: "Summer Hackathon: AI for Good",
    description: "48-hour hackathon building AI solutions for social impact, education, and healthcare.",
    location: "Rua dos Fanqueiros 80, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Beta-i",
    startDate: d(2026, 6, 5),
    endDate: d(2026, 6, 7),
    status: "draft",
    attendees: 0,
    capacity: 120,
    cost: 8000,
    revenue: null,
    currency: "EUR",
    category: "Hackathon",
    notes: null,
  },
  {
    name: "European CTO Summit",
    description: "Three-day summit for CTOs across Europe. Architecture decisions, team scaling, and tech strategy.",
    location: "Av. da Liberdade 245, Lisbon",
    country: "Portugal",
    city: "Lisbon",
    venueName: "Corinthia Lisbon",
    startDate: d(2026, 6, 17),
    endDate: d(2026, 6, 19),
    status: "draft",
    attendees: 0,
    capacity: 200,
    cost: 38000,
    revenue: null,
    currency: "EUR",
    category: "Summit",
    notes: null,
  },
  {
    name: "Zurich FinTech Forum",
    description: "Full-day forum on European fintech regulation, digital banking, and DeFi, hosted in Zurich.",
    location: "Talacker 42, Zurich",
    country: "Switzerland",
    city: "Zurich",
    venueName: "Impact Hub Zurich",
    startDate: d(2026, 6, 25),
    endDate: d(2026, 6, 25),
    status: "draft",
    attendees: 0,
    capacity: 90,
    cost: 7500,
    revenue: null,
    currency: "CHF",
    category: "Forum",
    notes: null,
  },
]

async function main() {
  console.log(`Seeding ${events.length} events...`)

  let created = 0
  let updated = 0

  for (const event of events) {
    const existing = await prisma.event.findFirst({
      where: {
        name: event.name,
        startDate: event.startDate,
      },
    })

    if (existing) {
      await prisma.event.update({
        where: { id: existing.id },
        data: event,
      })
      updated++
    } else {
      await prisma.event.create({
        data: event,
      })
      created++
    }
  }

  console.log(`Done! Created: ${created}, Updated: ${updated}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
